devicevlans:
  sales: { id: 50, mask: 255.255.255.0, stproot: dist1 }
  boss: { id: 60, mask: 255.255.255.0, stproot: dist2 }
vlans: "{{ devicevlans|combine(accessvlans) }}"

passiveospf:
  - port:
    - 'Ethernet0/2'
  - port:
    - 'Ethernet0/3'
  - port:
    - 'Ethernet1/1'

accessports:
  - ports:
    - 'Ethernet0/2'
    vlan: sales
  - ports:
    - 'Ethernet0/3'
    vlan: boss
  - ports:
    - 'Ethernet1/2 - 3'
    vlan: unusedvlan
  - ports:
    - 'Ethernet1/2 - 3'
    vlan: unusedvlan
  - ports:
    - 'Ethernet2/0 - 3'
    vlan: unusedvlan
  - ports:
    - 'Ethernet3/0 - 3'
    vlan: unusedvlan

trunks:
  - ports:
    - 'Ethernet0/0'
    - 'Ethernet0/1'

allowed_vlans: "{{ vlans.values()|map(attribute='id')|list|join(',') }}"